CREATE DATABASE HMS;

USE HMS;


CREATE TABLE USER(
    UID INT PRIMARY KEY AUTO_INCREMENT ,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100),
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(1000) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    ROLE VARCHAR(15) NOT NULL,
    USERPHOTO VARCHAR(1000)    
);

CREATE TABLE EMPLOYEE
(
    EID INT PRIMARY KEY AUTO_INCREMENT,
    DOJ DATE NOT NULL,
    DOB DATE NOT NULL,
    SALARY FLOAT NOT NULL,
    USERID INT,
    FOREIGN KEY (USERID) REFERENCES USER(UID) ON DELETE CASCADE
);

CREATE TABLE DOCTOR 
(
    DID INT PRIMARY KEY AUTO_INCREMENT,
    CHARGES VARCHAR(45),
    DEPARTMENT VARCHAR(100),
    EID INT,
    FOREIGN KEY(EID) REFERENCES EMPLOYEE(EID) ON DELETE CASCADE
);

CREATE TABLE PATIENT 
(
    PID INT PRIMARY KEY AUTO_INCREMENT,
    DID INT, 
    BLOODGROUP VARCHAR(4) NOT NULL,
    DOB DATE NOT NULL,
    PRESCRIPTION VARCHAR(1000),
    PATIENT_PROBLEM VARCHAR(1000),
    UID INT , 
    BED_NO INT,
    DOA DATE,
    DOD DATE,
    IS_ADMIT_P INT NOT NULL,
    IS_DOCTOR_VISITED INT NOT NULL,
    FOREIGN KEY (DID) REFERENCES DOCTOR(DID) ON DELETE CASCADE,
    FOREIGN KEY (UID) REFERENCES USER(UID) ON DELETE CASCADE
);

CREATE TABLE PAYMENT
(
    PAYID INT PRIMARY KEY AUTO_INCREMENT,
    FEES FLOAT NOT NULL,
    STATUS VARCHAR(45),
    PID INT,
    CATEGORY VARCHAR(100),
    FOREIGN KEY (PID) REFERENCES PATIENT(PID) ON DELETE CASCADE
);

CREATE TABLE APPOINTMENT
(
    APPID INT PRIMARY KEY AUTO_INCREMENT,
    STATUS VARCHAR(45),
    APPDATE DATE NOT NULL,
    DID INT ,
    PID INT,
    FOREIGN KEY (DID) REFERENCES DOCTOR(DID) ON DELETE CASCADE,
    FOREIGN KEY (PID) REFERENCES PATIENT(PID) ON DELETE CASCADE
);

CREATE TABLE MEDICIENE 
(
    MID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    PRICE FLOAT,
    QUANTITY INT,
    EXPIRYDATE DATE,
    DETAILS VARCHAR(100),
    PHOTO VARCHAR(1000)
);


